/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "WebBlog",
  "description": "WebBlog 前端笔记",
  "base": "/web-blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "shortcut icon",
        "href": "/web-blog/logo.png",
        "type": "image/x-icon"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "heroText": "WebBlog",
        "tagline": null,
        "actionText": "立刻学习 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "努力",
            "details": "努力的意义，就是，以后的日子里，放眼望去，全部都是自己喜欢的人和事！"
          },
          {
            "title": "等待",
            "details": "不要着急，最好的总会在最不经意的时候出现！"
          },
          {
            "title": "命运",
            "details": "岁月送给我苦难，也随赠我清醒与冷静。"
          }
        ],
        "footer": "感慨给你学习吧 |"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5906487d",
      "path": "/"
    },
    {
      "title": "打赏",
      "frontmatter": {},
      "regularPath": "/donate/",
      "relativePath": "donate/README.md",
      "key": "v-71dca5c0",
      "path": "/donate/"
    },
    {
      "title": "浏览器原理",
      "frontmatter": {},
      "regularPath": "/guide/browser/start.html",
      "relativePath": "guide/browser/start.md",
      "key": "v-c293abb8",
      "path": "/guide/browser/start.html",
      "headers": [
        {
          "level": 2,
          "title": "常⻅的浏览器内核有哪些",
          "slug": "常⻅的浏览器内核有哪些"
        },
        {
          "level": 2,
          "title": "浏览器的主要组成部分是什么",
          "slug": "浏览器的主要组成部分是什么"
        },
        {
          "level": 2,
          "title": "浏览器是如何渲染UI的",
          "slug": "浏览器是如何渲染ui的"
        },
        {
          "level": 2,
          "title": "浏览器如何解析css选择器",
          "slug": "浏览器如何解析css选择器"
        },
        {
          "level": 2,
          "title": "DOM Tree是如何构建的",
          "slug": "dom-tree是如何构建的"
        },
        {
          "level": 2,
          "title": "浏览器重绘与重排的区别",
          "slug": "浏览器重绘与重排的区别"
        },
        {
          "level": 2,
          "title": "如何触发重排和重绘",
          "slug": "如何触发重排和重绘"
        },
        {
          "level": 2,
          "title": "如何避免重绘或者重排",
          "slug": "如何避免重绘或者重排"
        },
        {
          "level": 2,
          "title": "前端如何实现即时通讯",
          "slug": "前端如何实现即时通讯"
        },
        {
          "level": 2,
          "title": "什么是浏览器同源策略",
          "slug": "什么是浏览器同源策略"
        },
        {
          "level": 2,
          "title": "如何实现跨域",
          "slug": "如何实现跨域"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-1fb04890",
      "path": "/guide/"
    },
    {
      "title": "CSS基础",
      "frontmatter": {},
      "regularPath": "/guide/css/start.html",
      "relativePath": "guide/css/start.md",
      "key": "v-58caaaf8",
      "path": "/guide/css/start.html",
      "headers": [
        {
          "level": 2,
          "title": "css三大特性 继承/优先级/层叠",
          "slug": "css三大特性-继承-优先级-层叠"
        },
        {
          "level": 2,
          "title": "css选择符分类",
          "slug": "css选择符分类"
        },
        {
          "level": 2,
          "title": "css优先级",
          "slug": "css优先级"
        },
        {
          "level": 3,
          "title": "另外一种理解方式：",
          "slug": "另外一种理解方式"
        },
        {
          "level": 3,
          "title": "需注意的：",
          "slug": "需注意的"
        },
        {
          "level": 2,
          "title": "css选择器的解析原则",
          "slug": "css选择器的解析原则"
        },
        {
          "level": 2,
          "title": "简洁、高效的css",
          "slug": "简洁、高效的css"
        },
        {
          "level": 2,
          "title": "link和@import的区别",
          "slug": "link和-import的区别"
        },
        {
          "level": 2,
          "title": "有哪些⽅式（CSS）可以隐藏⻚⾯元素",
          "slug": "有哪些方式-css-可以隐藏⻚面元素"
        },
        {
          "level": 2,
          "title": "em\\px\\rem区别",
          "slug": "em-px-rem区别"
        },
        {
          "level": 2,
          "title": "块级元素⽔平居中的⽅法",
          "slug": "块级元素水平居中的方法"
        },
        {
          "level": 2,
          "title": "css有⼏种定位⽅式",
          "slug": "css有几种定位方式"
        },
        {
          "level": 2,
          "title": "如何理解z-index",
          "slug": "如何理解z-index"
        },
        {
          "level": 2,
          "title": "如何理解层叠上下文",
          "slug": "如何理解层叠上下文"
        },
        {
          "level": 2,
          "title": "清除浮动有哪些⽅法",
          "slug": "清除浮动有哪些方法"
        },
        {
          "level": 2,
          "title": "你对css-sprites的理解",
          "slug": "你对css-sprites的理解"
        },
        {
          "level": 2,
          "title": "你对媒体查询的理解",
          "slug": "你对媒体查询的理解"
        },
        {
          "level": 2,
          "title": "你对盒模型的理解",
          "slug": "你对盒模型的理解"
        },
        {
          "level": 2,
          "title": "标准盒模型和怪异盒模型有什么区别",
          "slug": "标准盒模型和怪异盒模型有什么区别"
        },
        {
          "level": 2,
          "title": "谈谈对BFC(Block Formatting Context)的理解",
          "slug": "谈谈对bfc-block-formatting-context-的理解"
        },
        {
          "level": 2,
          "title": "为什么有时候⼈们⽤translate来改变位置⽽不是定位",
          "slug": "为什么有时候人们用translate来改变位置而不是定位"
        },
        {
          "level": 2,
          "title": "伪类和伪元素的区别是什么",
          "slug": "伪类和伪元素的区别是什么"
        },
        {
          "level": 2,
          "title": "你对flex的理解",
          "slug": "你对flex的理解"
        },
        {
          "level": 2,
          "title": "关于CSS的动画与过渡问题",
          "slug": "关于css的动画与过渡问题"
        }
      ]
    },
    {
      "title": "dom",
      "frontmatter": {},
      "regularPath": "/guide/dom/start.html",
      "relativePath": "guide/dom/start.md",
      "key": "v-a636f638",
      "path": "/guide/dom/start.html",
      "headers": [
        {
          "level": 2,
          "title": "dom",
          "slug": "dom"
        },
        {
          "level": 2,
          "title": "DOM的事件模型是什么",
          "slug": "dom的事件模型是什么"
        },
        {
          "level": 2,
          "title": "DOM的事件流是什么",
          "slug": "dom的事件流是什么"
        },
        {
          "level": 2,
          "title": "什么是事件委托",
          "slug": "什么是事件委托"
        }
      ]
    },
    {
      "title": "html基础",
      "frontmatter": {
        "title": "html基础",
        "author": "小虎",
        "date": "2022-09-15"
      },
      "regularPath": "/guide/html/start.html",
      "relativePath": "guide/html/start.md",
      "key": "v-76f6f0a8",
      "path": "/guide/html/start.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML、XML 和 XHTML 有什么区别？",
          "slug": "html、xml-和-xhtml-有什么区别"
        }
      ]
    },
    {
      "title": "HTML面试题整理",
      "frontmatter": {
        "title": "HTML面试题整理",
        "author": "小虎",
        "date": "2022-09-15"
      },
      "regularPath": "/guide/html/start1.html",
      "relativePath": "guide/html/start1.md",
      "key": "v-607c4d5e",
      "path": "/guide/html/start1.html",
      "headers": [
        {
          "level": 2,
          "title": "01.说一下对语义化的理解？✅",
          "slug": "_01-说一下对语义化的理解-✅"
        },
        {
          "level": 2,
          "title": "02.说一下HTML5有哪些更新/新增？✅",
          "slug": "_02-说一下html5有哪些更新-新增-✅"
        },
        {
          "level": 2,
          "title": "03.说一下defer和async的区别？✅",
          "slug": "_03-说一下defer和async的区别-✅"
        },
        {
          "level": 2,
          "title": "04.说一下iframe有哪些优点和缺点？✅",
          "slug": "_04-说一下iframe有哪些优点和缺点-✅"
        },
        {
          "level": 2,
          "title": "05.说一下web worker?✅",
          "slug": "_05-说一下web-worker-✅"
        },
        {
          "level": 2,
          "title": "06.行内，块级，空元素，替换元素有哪些？✅",
          "slug": "_06-行内-块级-空元素-替换元素有哪些-✅"
        },
        {
          "level": 2,
          "title": "07.DOCTYPE的作用？严格模式和混杂模式的区别？",
          "slug": "_07-doctype的作用-严格模式和混杂模式的区别"
        },
        {
          "level": 2,
          "title": "08.说一下渐进增强和优雅降级的区别？",
          "slug": "_08-说一下渐进增强和优雅降级的区别"
        },
        {
          "level": 2,
          "title": "09.说一下常见的meta标签属性和作用？",
          "slug": "_09-说一下常见的meta标签属性和作用"
        },
        {
          "level": 2,
          "title": "10.说一下HTML5的离线存储？",
          "slug": "_10-说一下html5的离线存储"
        },
        {
          "level": 2,
          "title": "11.说一下怎么做好seo？",
          "slug": "_11-说一下怎么做好seo"
        },
        {
          "level": 2,
          "title": "12.说一下b和strong，i和em的区别？",
          "slug": "_12-说一下b和strong-i和em的区别"
        },
        {
          "level": 2,
          "title": "13.说一下img的srcset作用？alt和title的区别?",
          "slug": "_13-说一下img的srcset作用-alt和title的区别"
        },
        {
          "level": 2,
          "title": "14.说一下canvas和svg的区别？",
          "slug": "_14-说一下canvas和svg的区别"
        },
        {
          "level": 2,
          "title": "15.说一下drag api？",
          "slug": "_15-说一下drag-api"
        },
        {
          "level": 2,
          "title": "16.说一下label的作用？",
          "slug": "_16-说一下label的作用"
        },
        {
          "level": 2,
          "title": "17.说一下src和href的区别？",
          "slug": "_17-说一下src和href的区别"
        },
        {
          "level": 2,
          "title": "18.说一下音视频标签的使用？",
          "slug": "_18-说一下音视频标签的使用"
        }
      ]
    },
    {
      "title": "js基础",
      "frontmatter": {},
      "regularPath": "/guide/js/start.html",
      "relativePath": "guide/js/start.md",
      "key": "v-09517528",
      "path": "/guide/js/start.html",
      "headers": [
        {
          "level": 2,
          "title": "谈谈你对原型链的理解",
          "slug": "谈谈你对原型链的理解"
        },
        {
          "level": 2,
          "title": "如何判断是否是数组",
          "slug": "如何判断是否是数组"
        },
        {
          "level": 2,
          "title": "ES6模块与CommonJS模块有什么区别",
          "slug": "es6模块与commonjs模块有什么区别"
        },
        {
          "level": 2,
          "title": "聊⼀聊如何在JavaScript中实现不可变对象",
          "slug": "聊一聊如何在javascript中实现不可变对象"
        },
        {
          "level": 2,
          "title": "JavaScript的参数是按照什么⽅式传递的",
          "slug": "javascript的参数是按照什么方式传递的"
        },
        {
          "level": 2,
          "title": "js有哪些类型",
          "slug": "js有哪些类型"
        },
        {
          "level": 2,
          "title": "为什么会有BigInt的提案",
          "slug": "为什么会有bigint的提案"
        },
        {
          "level": 2,
          "title": "null与undefined的区别是什么",
          "slug": "null与undefined的区别是什么"
        },
        {
          "level": 2,
          "title": "0.1+0.2为什么不等于0.3",
          "slug": "_0-1-0-2为什么不等于0-3"
        },
        {
          "level": 2,
          "title": "类型转换的规则有哪些",
          "slug": "类型转换的规则有哪些"
        },
        {
          "level": 2,
          "title": "类型转换的原理是什么",
          "slug": "类型转换的原理是什么"
        },
        {
          "level": 2,
          "title": "JS常用数据结构",
          "slug": "js常用数据结构"
        }
      ]
    },
    {
      "title": "js机制",
      "frontmatter": {},
      "regularPath": "/guide/js/start1.html",
      "relativePath": "guide/js/start1.md",
      "key": "v-7598355e",
      "path": "/guide/js/start1.html",
      "headers": [
        {
          "level": 2,
          "title": "解释下变量提升",
          "slug": "解释下变量提升"
        },
        {
          "level": 2,
          "title": "⼀段js代码是如何执⾏的",
          "slug": "一段js代码是如何执行的"
        },
        {
          "level": 2,
          "title": "执行上下文",
          "slug": "执行上下文"
        },
        {
          "level": 2,
          "title": "js的作⽤域链理解吗",
          "slug": "js的作用域链理解吗"
        },
        {
          "level": 2,
          "title": "谈⼀谈你对this的了解",
          "slug": "谈一谈你对this的了解"
        },
        {
          "level": 2,
          "title": "箭头函数的this指向哪⾥",
          "slug": "箭头函数的this指向哪里"
        },
        {
          "level": 2,
          "title": "理解闭包吗",
          "slug": "理解闭包吗"
        }
      ]
    },
    {
      "title": "js内存",
      "frontmatter": {},
      "regularPath": "/guide/js/start2.html",
      "relativePath": "guide/js/start2.md",
      "key": "v-09054a04",
      "path": "/guide/js/start2.html",
      "headers": [
        {
          "level": 2,
          "title": "讲讲JavaScript垃圾回收是怎么做的",
          "slug": "讲讲javascript垃圾回收是怎么做的"
        },
        {
          "level": 2,
          "title": "js的基本类型和复杂类型是储存在哪⾥的",
          "slug": "js的基本类型和复杂类型是储存在哪里的"
        }
      ]
    },
    {
      "title": "typescript",
      "frontmatter": {},
      "regularPath": "/guide/ts/start.html",
      "relativePath": "guide/ts/start.md",
      "key": "v-1d8d5900",
      "path": "/guide/ts/start.html",
      "headers": [
        {
          "level": 2,
          "title": "ts与js相比较有哪些优势",
          "slug": "ts与js相比较有哪些优势"
        },
        {
          "level": 2,
          "title": "TypeScript 中的原始类型有哪些",
          "slug": "typescript-中的原始类型有哪些"
        },
        {
          "level": 2,
          "title": "说说数组在 TypeScript 中是如何工作的",
          "slug": "说说数组在-typescript-中是如何工作的"
        },
        {
          "level": 2,
          "title": "any/void/never 类型，何时使用",
          "slug": "any-void-never-类型-何时使用"
        },
        {
          "level": 2,
          "title": "TypeScript 中声明变量有哪些不同的关键字",
          "slug": "typescript-中声明变量有哪些不同的关键字"
        },
        {
          "level": 2,
          "title": "如何书写带有类型注释的函数",
          "slug": "如何书写带有类型注释的函数"
        },
        {
          "level": 2,
          "title": "如何在 TypeScript 中创建对象",
          "slug": "如何在-typescript-中创建对象"
        },
        {
          "level": 2,
          "title": "如何在 TypeScript 中指定可选属性",
          "slug": "如何在-typescript-中指定可选属性"
        },
        {
          "level": 2,
          "title": "说说枚举在 TypeScript 中是如何工作的",
          "slug": "说说枚举在-typescript-中是如何工作的"
        },
        {
          "level": 2,
          "title": "说说TypeScript 中 for 循环的不同变体",
          "slug": "说说typescript-中-for-循环的不同变体"
        },
        {
          "level": 2,
          "title": "类型注解和类型别名有什么区别",
          "slug": "类型注解和类型别名有什么区别"
        },
        {
          "level": 2,
          "title": "类型别名和interface区别是什么",
          "slug": "类型别名和interface区别是什么"
        },
        {
          "level": 2,
          "title": "谈谈你对泛型的认识",
          "slug": "谈谈你对泛型的认识"
        },
        {
          "level": 2,
          "title": "ts中class类有哪些属性",
          "slug": "ts中class类有哪些属性"
        },
        {
          "level": 2,
          "title": "文件声明的关键字是什么",
          "slug": "文件声明的关键字是什么"
        },
        {
          "level": 2,
          "title": "ts如何实现模块化开发",
          "slug": "ts如何实现模块化开发"
        },
        {
          "level": 2,
          "title": "你认为ts开发中，开发过程是什么",
          "slug": "你认为ts开发中-开发过程是什么"
        }
      ]
    },
    {
      "title": "js异步",
      "frontmatter": {},
      "regularPath": "/guide/js/start3.html",
      "relativePath": "guide/js/start3.md",
      "key": "v-fd3afec4",
      "path": "/guide/js/start3.html",
      "headers": [
        {
          "level": 2,
          "title": "async/await 是什么",
          "slug": "async-await-是什么"
        },
        {
          "level": 2,
          "title": "async/await 相⽐于Promise的优势",
          "slug": "async-await-相比于promise的优势"
        }
      ]
    },
    {
      "title": "TS「面试题及答案」",
      "frontmatter": {},
      "regularPath": "/guide/ts/start1.html",
      "relativePath": "guide/ts/start1.md",
      "key": "v-32af6d9e",
      "path": "/guide/ts/start1.html"
    },
    {
      "title": "虚拟dom",
      "frontmatter": {
        "title": "虚拟dom",
        "author": "小虎",
        "date": "2022-09-15"
      },
      "regularPath": "/guide/react/start.html",
      "relativePath": "guide/react/start.md",
      "key": "v-e50b73f8",
      "path": "/guide/react/start.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是虚拟dom",
          "slug": "什么是虚拟dom"
        },
        {
          "level": 2,
          "title": "虚拟DOM VS 直接操作原生DOM？",
          "slug": "虚拟dom-vs-直接操作原生dom"
        },
        {
          "level": 2,
          "title": "虚拟DOM VS MVVM？",
          "slug": "虚拟dom-vs-mvvm"
        },
        {
          "level": 2,
          "title": "对React虚拟DOM的误解？",
          "slug": "对react虚拟dom的误解"
        },
        {
          "level": 2,
          "title": "react 合成事件",
          "slug": "react-合成事件"
        },
        {
          "level": 2,
          "title": "谈谈你对react fiber 结构理解",
          "slug": "谈谈你对react-fiber-结构理解"
        },
        {
          "level": 2,
          "title": "react 中key是什么?有什么作用？",
          "slug": "react-中key是什么-有什么作用"
        },
        {
          "level": 2,
          "title": "组件通信有哪些方式？",
          "slug": "组件通信有哪些方式"
        },
        {
          "level": 2,
          "title": "react合成事件机制",
          "slug": "react合成事件机制"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "教程",
        "link": "/guide/"
      },
      {
        "text": "Github",
        "link": "https://github.com/xiaohuooo"
      },
      {
        "text": "CSDN",
        "link": "https://blog.csdn.net/qq_55172460",
        "target": "_blank"
      },
      {
        "text": "掘金",
        "link": "https://juejin.cn/user/558968298809645",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ],
    "navbar": true,
    "markdown": {
      "anchor": {
        "permalink": false
      },
      "toc": {
        "includeLevel": [
          1,
          2,
          3
        ]
      },
      "lineNumbers": true
    },
    "sidebar": {
      "collapsable": false,
      "/guide/": [
        {
          "title": "CSS",
          "collapsable": true,
          "children": [
            "css/start"
          ]
        },
        {
          "title": "JS",
          "collapsable": true,
          "children": [
            "js/start",
            "js/start1",
            "js/start2",
            "js/start3"
          ]
        },
        {
          "title": "HTML",
          "collapsable": true,
          "children": [
            "html/start",
            "html/start1"
          ]
        },
        {
          "title": "React",
          "collapsable": true,
          "children": [
            "react/start"
          ]
        },
        {
          "title": "TS",
          "collapsable": true,
          "children": [
            "ts/start",
            "ts/start1"
          ]
        },
        {
          "title": "浏览器",
          "collapsable": true,
          "children": [
            "browser/start"
          ]
        },
        {
          "title": "DOM",
          "collapsable": true,
          "children": [
            "dom/start"
          ]
        }
      ]
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}